HIGH_RISK_PROTOCOLS:
    TCP:
        - 20-21
        - 23
        - 80
        - 5800
        - 5900
        - 8080
    UDP:
        - 69
    ICMP:
    
DESTINATION_PORT_CATEGORIES:
    HIGH: 16
    MEDIUM: 8
    LOW: 4

SOURCE_NETWORK_CATEGORIES:
    HIGH: /16
    MEDIUM: /19
    LOW: 2048
    
DESTINATION_NETWORK_CATEGORIES:
    HIGH: /22
    MEDIUM: /24
    LOW: 16
    
RELATIVE_SOURCE_NETWORK_CATEGORIES:
    HIGH: 10
    MEDIUM: 5
    LOW: 3
    
RELATIVE_DESTINATION_NETWORK_CATEGORIES:
    HIGH: 10
    MEDIUM: 5
    LOW: 3

RELATIVE_DESTINATION_PORT_CATEGORIES:
    HIGH: 10
    MEDIUM: 5
    LOW: 3
